# Generated by Django 3.2.12 on 2022-03-15 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga_Emprego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidadeVagas', models.IntegerField(validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('vaga', models.CharField(max_length=60)),
                ('empresa', models.CharField(max_length=60)),
                ('cnpj', models.IntegerField()),
                ('endereco', models.CharField(max_length=60)),
                ('telefone', models.IntegerField()),
                ('escolaridade', models.CharField(max_length=60)),
                ('experiencia', models.CharField(choices=[(1, 'Sim'), (0, 'Não')], max_length=10)),
                ('formaDeContato', models.CharField(max_length=60)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
            ],
            options={
                'verbose_name': 'Vaga de Emprego',
                'verbose_name_plural': 'Vadas de Emprego',
                'ordering': ['empresa'],
            },
        ),
    ]
