# Generated by Django 3.2.12 on 2022-04-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga_emprego',
            name='cnpj',
        ),
    ]
