# Generated by Django 3.2.12 on 2022-04-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ocultar',
            field=models.BooleanField(choices=[(True, 'Ocultar informações da empresa ao encaminhar'), (False, 'Exibir informações da empresa ao encaminhar')], default=True, verbose_name='Informações da empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='formaDeContato',
            field=models.CharField(choices=[('T', 'TELEFONE'), ('E', 'EMAIL'), ('P', 'PRESENCIAL')], max_length=1, verbose_name='Forma de contato'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(max_length=11, verbose_name='Telefone'),
        ),
    ]
