# Generated by Django 3.2.12 on 2022-03-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga_emprego',
            name='experiencia',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Experiência'),
        ),
    ]
