# Generated by Django 3.2.12 on 2022-04-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_auto_20220412_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True, verbose_name='CNPJ da empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nome da empresa'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome da vaga'),
        ),
    ]
