# Generated by Django 3.2.12 on 2022-04-18 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vagas', '0003_auto_20220412_1737'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vaga',
            new_name='Cargo',
        ),
        migrations.RenameField(
            model_name='vaga_emprego',
            old_name='vaga',
            new_name='cargo',
        ),
        migrations.AlterField(
            model_name='escolaridade',
            name='nome',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nome da escolaridade'),
        ),
    ]
