# Generated by Django 3.2.12 on 2022-05-11 14:31

from django.db import migrations, models
import vagas.validations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0004_auto_20220418_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='contato_email',
            field=models.BooleanField(default=False, verbose_name='Contato por email'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True, validators=[vagas.validations.validate_CNPJ], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=150, unique=True, verbose_name='NOME'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(max_length=11, validators=[vagas.validations.validate_TELEFONE], verbose_name='Telefone'),
        ),
    ]
