# Generated by Django 3.2.12 on 2022-05-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0005_auto_20220511_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='contato_presencial',
            field=models.BooleanField(default=False, verbose_name='Contato presencial'),
        ),
    ]
