# Generated by Django 3.2.12 on 2022-05-11 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0007_empresa_contato_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='formaDeContato',
        ),
    ]
