# Generated by Django 3.2.12 on 2022-05-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0008_remove_empresa_formadecontato'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga_emprego',
            name='atribuicoes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
