# Generated by Django 3.2.12 on 2022-05-11 17:48

from django.db import migrations, models
import vagas.validations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0010_auto_20220511_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='contato_whatsapp',
            field=models.BooleanField(default=False, verbose_name='Contato por whatsapp'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email p/ encaminhamento'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='endereco',
            field=models.CharField(blank=True, max_length=60, verbose_name='Endereço p/ encaminhamento'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, validators=[vagas.validations.validate_TELEFONE], verbose_name='Telefone p/ encaminhamento'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=11, validators=[vagas.validations.validate_TELEFONE], verbose_name='Whatsapp p/ encaminhamento'),
        ),
    ]
